### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by YDX-2147483647** [titaneric/typst-mixed-resume#1]
This is a great template, but could you license it?

FYI, https://github.com/Harkunwar/attractive-typst-resume and https://github.com/GeorgeHoneywood/alta-typst uses MIT license, and https://github.com/giovanniberti/moderncv.typst uses Apache-2.0 license.

Here's [_Adding a license to a repository_](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) from GitHub Docs.

**Comment by titaneric** [comment]
Thank for noticing me this important issue, I will use MIT license

**Comment by titaneric** [comment]
Close it as adding MIT license
